"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pagination import Pagination, PaginationTypedDict
from .repository_output import RepositoryOutput, RepositoryOutputTypedDict
from polar.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class ListResourceRepositoryTypedDict(TypedDict):
    pagination: PaginationTypedDict
    items: NotRequired[List[RepositoryOutputTypedDict]]
    

class ListResourceRepository(BaseModel):
    pagination: Pagination
    items: Optional[List[RepositoryOutput]] = None
    
