"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customerbenefitgrantslacksharedchannelpropertiesupdate import (
    CustomerBenefitGrantSlackSharedChannelPropertiesUpdate,
    CustomerBenefitGrantSlackSharedChannelPropertiesUpdateTypedDict,
)
from polar_sdk.types import BaseModel
from polar_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class CustomerBenefitGrantSlackSharedChannelUpdateTypedDict(TypedDict):
    properties: CustomerBenefitGrantSlackSharedChannelPropertiesUpdateTypedDict
    benefit_type: Literal["slack_shared_channel"]


class CustomerBenefitGrantSlackSharedChannelUpdate(BaseModel):
    properties: CustomerBenefitGrantSlackSharedChannelPropertiesUpdate

    BENEFIT_TYPE: Annotated[
        Annotated[
            Literal["slack_shared_channel"],
            AfterValidator(validate_const("slack_shared_channel")),
        ],
        pydantic.Field(alias="benefit_type"),
    ] = "slack_shared_channel"
