"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .listresource_paymentmethod_ import (
    ListResourcePaymentMethod,
    ListResourcePaymentMethodTypedDict,
)
from polar_sdk.types import BaseModel
from polar_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing import Callable, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CustomersListPaymentMethodsExternalRequestTypedDict(TypedDict):
    external_id: str
    r"""The customer external ID."""
    page: NotRequired[int]
    r"""Page number, defaults to 1."""
    limit: NotRequired[int]
    r"""Size of a page, defaults to 10. Maximum is 100."""


class CustomersListPaymentMethodsExternalRequest(BaseModel):
    external_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The customer external ID."""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Page number, defaults to 1."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""Size of a page, defaults to 10. Maximum is 100."""


class CustomersListPaymentMethodsExternalResponseTypedDict(TypedDict):
    result: ListResourcePaymentMethodTypedDict


class CustomersListPaymentMethodsExternalResponse(BaseModel):
    next: Callable[[], Optional[CustomersListPaymentMethodsExternalResponse]]

    result: ListResourcePaymentMethod
