"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from polar_sdk.types import BaseModel
from polar_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated, TypedDict


class CustomerBenefitGrantLicenseKeysUpdateBenefitType(str, Enum):
    LICENSE_KEYS = "license_keys"


class CustomerBenefitGrantLicenseKeysUpdateTypedDict(TypedDict):
    benefit_type: CustomerBenefitGrantLicenseKeysUpdateBenefitType


class CustomerBenefitGrantLicenseKeysUpdate(BaseModel):
    BENEFIT_TYPE: Annotated[
        Annotated[
            CustomerBenefitGrantLicenseKeysUpdateBenefitType,
            AfterValidator(
                validate_const(
                    CustomerBenefitGrantLicenseKeysUpdateBenefitType.LICENSE_KEYS
                )
            ),
        ],
        pydantic.Field(alias="benefit_type"),
    ] = CustomerBenefitGrantLicenseKeysUpdateBenefitType.LICENSE_KEYS
