"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customerportalmemberupdate import (
    CustomerPortalMemberUpdate,
    CustomerPortalMemberUpdateTypedDict,
)
from polar_sdk.types import BaseModel
from polar_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class CustomerPortalMembersUpdateMemberRequestTypedDict(TypedDict):
    id: str
    customer_portal_member_update: CustomerPortalMemberUpdateTypedDict


class CustomerPortalMembersUpdateMemberRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    customer_portal_member_update: Annotated[
        CustomerPortalMemberUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
