"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from polar_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OrganizationFeatureSettingsTypedDict(TypedDict):
    issue_funding_enabled: NotRequired[bool]
    r"""If this organization has issue funding enabled"""
    usage_based_billing_enabled: NotRequired[bool]
    r"""If this organization has usage-based billing enabled"""


class OrganizationFeatureSettings(BaseModel):
    issue_funding_enabled: Optional[bool] = False
    r"""If this organization has issue funding enabled"""

    usage_based_billing_enabled: Optional[bool] = False
    r"""If this organization has usage-based billing enabled"""
