"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subscriptionprorationbehavior import SubscriptionProrationBehavior
from polar_sdk.types import BaseModel
from typing_extensions import TypedDict


class SubscriptionUpdatedProductMetadataTypedDict(TypedDict):
    subscription_id: str
    product_id: str
    proration_behavior: SubscriptionProrationBehavior


class SubscriptionUpdatedProductMetadata(BaseModel):
    subscription_id: str

    product_id: str

    proration_behavior: SubscriptionProrationBehavior
