"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .benefitgrantwebhook import BenefitGrantWebhook, BenefitGrantWebhookTypedDict
from enum import Enum
from polar_sdk.types import BaseModel
import pydantic
from typing import Final, TypedDict
from typing_extensions import Annotated


class WebhookBenefitGrantCreatedPayloadType(str, Enum):
    BENEFIT_GRANT_CREATED = "benefit_grant.created"


class WebhookBenefitGrantCreatedPayloadTypedDict(TypedDict):
    r"""Sent when a new benefit grant is created.

    **Discord & Slack support:** Basic
    """

    data: BenefitGrantWebhookTypedDict
    type: WebhookBenefitGrantCreatedPayloadType


class WebhookBenefitGrantCreatedPayload(BaseModel):
    r"""Sent when a new benefit grant is created.

    **Discord & Slack support:** Basic
    """

    data: BenefitGrantWebhook

    # fmt: off
    TYPE: Annotated[Final[WebhookBenefitGrantCreatedPayloadType], pydantic.Field(alias="type")] = WebhookBenefitGrantCreatedPayloadType.BENEFIT_GRANT_CREATED # type: ignore
    # fmt: on
